-- Run once in the Supabase SQL editor for the public MINE AI waitlist.
create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null,
  created_at timestamptz not null default now(),
  constraint waitlist_email_format check (email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')
);

create unique index if not exists waitlist_email_unique
  on public.waitlist (lower(email));

alter table public.waitlist enable row level security;

revoke all on table public.waitlist from anon, authenticated;
grant insert on table public.waitlist to anon, authenticated;
grant usage, select on sequence public.waitlist_id_seq to anon, authenticated;

drop policy if exists "Public can join waitlist" on public.waitlist;
create policy "Public can join waitlist"
  on public.waitlist
  for insert
  to anon, authenticated
  with check (length(email) between 5 and 254);
