import type { Metadata } from 'next';
import { LegalLayout } from '@/components/site-shell';
import { EFFECTIVE_DATE, SITE } from '@/lib/site';
export const metadata:Metadata={title:'Privacy Policy | MINE AI',description:'How MINE AI collects, uses, processes and protects personal information.',alternates:{canonical:'/privacy'}};
export default function Privacy(){return <LegalLayout eyebrow="Legal" title="Privacy Policy" intro={`Effective ${EFFECTIVE_DATE}. This policy explains how MINE AI handles information when you use the app, website and related services.`}>
<h2>1. What MINE AI is</h2><p>MINE AI is a personal AI life-planning app that helps turn natural-language plans into a structured day, including tasks, timing, routines and reminders.</p>
<h2>2. Information you provide</h2><p>Depending on how you use MINE AI, you may provide account details such as your email address, name and profile information; typed or transcribed planning input; tasks and items; routines and routine logs; Memory or closed-day history; and messages you send to support.</p><p>For signed-in users, cloud data may include a profile, tasks or items, routines, routine logs, Memory or day records, AI usage metadata, device push tokens and AI content reports.</p>
<h2>3. Voice and audio processing</h2><p>When you use voice planning, the app first records audio temporarily in the device cache. The audio is sent through a Supabase Edge Function to OpenAI’s Whisper service for transcription, and a transcript is returned to MINE AI.</p><div className="flow">Device cache <span>→</span> Supabase Edge Function <span>→</span> OpenAI Whisper <span>→</span> Transcript</div><p>MINE AI does not write voice audio into Supabase Storage or a permanent audio database. Temporary audio cleanup is best-effort and may not complete immediately if the app or process terminates abruptly. Third-party processing and retention are governed by the applicable provider policies or agreements; we do not state a fixed vendor retention period where one has not been established.</p>
<h2>4. AI planning</h2><p>Your typed or transcribed input, together with relevant profile and day context, is sent through Supabase to Anthropic to produce a structured plan.</p><div className="flow">Input + relevant context <span>→</span> Supabase <span>→</span> Anthropic <span>→</span> Structured plan</div><p>AI output may be incomplete or inaccurate. Review a plan before relying on it, especially when timing, health, safety, finances or other important decisions are involved.</p>
<h2>5. AI content reporting</h2><p>If you report AI-generated content, the report may include the specific generated content, your selected reason, an optional note, a user ID or installation ID, a timestamp, and app or platform metadata. We use reports to review issues and improve safety and quality.</p>
<h2>6. Device and local information</h2><p>MINE AI may use device or installation identifiers, app and platform metadata, and push notification identifiers needed to operate the service and deliver requested reminders. The app may store data locally using device storage such as AsyncStorage, including preferences, cached state or locally available planning information.</p>
<h2>7. How information is used</h2><ul><li>Provide planning, transcription, reminders, sync and account features.</li><li>Maintain, troubleshoot and improve the service.</li><li>Monitor AI usage and enforce applicable limits.</li><li>Review AI content reports and respond to support or privacy requests.</li><li>Protect users, the service and our legal rights.</li></ul>
<h2>8. Processors and disclosures</h2><p>We use service providers to operate MINE AI, including Supabase for backend and data processing, OpenAI for voice transcription, and Anthropic for AI planning. Those providers process information on our behalf or as otherwise described in their terms and privacy materials. We may also disclose information when required by law, to protect rights or safety, or as part of a business transfer subject to appropriate safeguards.</p><p>MINE AI does not sell personal data.</p>
<h2>9. Retention</h2><p>We keep account-linked information for as long as reasonably needed to provide MINE AI, meet legal obligations, resolve disputes and protect the service. Retention can vary by data type and account status. Temporary files may persist longer than intended after abrupt termination. Provider retention is governed by provider policies or agreements where exact periods have not been established by MINE AI.</p>
<h2>10. Account deletion</h2><p>You can request permanent deletion in the app through <strong>Me → Delete Account</strong> or initiate a verified request on the <a href="/delete-account">Delete Account page</a>. Deletion may remove your profile, tasks, routines, routine logs, Memory or day history, push registrations, account-linked AI usage records, signed-in AI reports and other account-linked app data. Some limited information may be retained where reasonably required by law, security, fraud prevention or dispute resolution.</p>
<h2>11. Security</h2><p>MINE AI uses secure HTTPS connections and reasonable technical and organizational safeguards. No storage or transmission method is completely secure, so we cannot guarantee absolute security.</p>
<h2>12. Children</h2><p>MINE AI is intended for a general audience able to use the service lawfully and is not directed to children under 13. If you believe a child has provided personal information contrary to applicable law, contact us.</p>
<h2>13. International processing</h2><p>Our providers may process information in countries other than your own. Where required, we seek to use appropriate contractual or legal safeguards, recognizing that privacy laws vary by location.</p>
<h2>14. Your choices and rights</h2><p>You can manage app information, notification permissions and account deletion as described above. Depending on your location, you may have additional rights to access, correct, delete or restrict processing of personal information. Contact us to make a request; we may need to verify your identity.</p>
<h2>15. Changes and contact</h2><p>We may update this policy as MINE AI evolves. We will post the updated policy with a revised effective date and provide additional notice when appropriate. Questions or requests can be sent to <a href={`mailto:${SITE.supportEmail}`}>{SITE.supportEmail}</a>.</p>
</LegalLayout>}
