import Link from 'next/link';
import { Footer, Header } from '@/components/site-shell';
import { PRICING, ROUTES } from '@/lib/site';

const heroPlan=[['3:30 PM','Groceries','Errand · 45 min'],['5:00 PM',"Mom’s appointment",'Family · 1 hour'],['7:30 PM','Prepare dinner','Home · 45 min']];
const steps=[['01','Tell MINE AI what’s happening','Speak or type naturally. No tidying your thoughts first.'],['02','MINE AI understands the day','It identifies tasks, timing, routines and the details that matter.'],['03','Review your plan','See a clear day and adjust anything that needs your touch.'],['04','Stay on track','Timely reminders help the plan survive a busy day.']];
const features=[['Voice planning','Talk instead of typing every little task. English voice transcription is supported in V1.'],['Typed planning','Pour out the details in your own words—short, long or a little messy.'],['A structured day','Turn real-life input into tasks, times and a clear Today view.'],['Plans & routines','Keep one-off tasks, calendar plans and recurring rhythms together.'],['Memory','Look back at closed days and the things you have already handled.'],['Helpful reminders','Get nudges that keep the day moving without living in your planner.'],['Cloud sync','Signed-in users can keep their planning data available across supported devices.'],['Your control','Delete your account or report AI-generated content from the app.']];
const people=[['Student','Classes, assignments, errands and a social life—all in the same day.'],['Parent','School runs, appointments, dinner and the things everyone needs from you.'],['Professional','Meetings, focus time and life outside work, planned together.'],['Busy life','For the days when everything feels important and nothing arrives in order.']];
const faqs=[['What is MINE AI?','MINE AI is a personal AI life planner. You tell it what is happening, and it helps shape those details into a structured day.'],['Who is it for?','Students, parents, employees, teachers, professionals and anyone balancing work with personal life.'],['Can I use voice?','Yes. Voice planning lets you speak naturally instead of typing every detail.'],['Does MINE AI support multiple languages?','MINE AI V1 currently supports English voice transcription.'],['How does MINE AI use AI?','MINE AI sends typed or transcribed planning input, plus relevant profile and day context, through its service to an AI provider to create a structured plan.'],['Is my voice stored?','Voice is temporarily processed for transcription and is not intentionally stored by MINE AI as a permanent audio library. Temporary cleanup is best-effort; see the Privacy Policy for details.'],['Can I delete my account?','Yes. Delete it in the app or initiate a verified deletion request from this website.'],['Is MINE AI free?','A free experience is planned, with limited AI planning and core daily organization. Pro is planned at $7.99 per month; availability may vary during early access.'],['When will MINE AI be available?','MINE AI is currently preparing for public Android release. Join early access to follow availability.']];

function PhonePlan(){return <div className="phone"><div className="phone-top"><span>9:41</span><span className="island"/><span>● ◒</span></div><div className="phone-content"><div className="app-greeting"><div><small>YOUR DAY</small><h2>Tomorrow</h2></div><span className="avatar">M</span></div><div className="day-progress"><span/><span/><span/><span/></div><p className="plan-ready"><span>✦</span>Your plan is ready</p><div className="schedule">{heroPlan.map(([time,task,meta],i)=><div className="schedule-row" key={task}><time>{time}</time><span className={`dot dot-${i}`}/><div><strong>{task}</strong><small>{meta}</small></div></div>)}</div><div className="review-button">Review my plan</div></div></div>}
export default function Home(){return <><Header/><main>
  <section className="hero shell"><div className="hero-copy"><p className="eyebrow"><span/>A calmer way to plan</p><h1>Tell MINE AI what’s happening.<br/><em>It turns your day into a plan.</em></h1><p className="lede">Speak or type your day naturally. MINE AI helps organize tasks, timing, routines and reminders so you can focus on living it.</p><div className="hero-actions"><a href="#early-access" className="button">Get early access <span aria-hidden>→</span></a><a href="#how-it-works" className="text-link">See how it works <span aria-hidden>↓</span></a></div><p className="availability"><span>Android</span>Preparing for public release</p></div><div className="hero-visual" aria-label="MINE AI planning example"><div className="glow"/><div className="thought-card"><div className="thought-top"><span className="pulse"/><span>You tell MINE AI</span><span className="wave">▂▄▆▃▅</span></div><p>“Tomorrow I work until 3, need groceries, mom has an appointment, and friends are coming for dinner.”</p></div><PhonePlan/></div></section>
  <section className="problem section"><div className="shell problem-grid"><div><p className="section-kicker">Real life, understood</p><h2>Life doesn’t arrive<br/>as a to-do list.</h2></div><div><p className="big-copy">It arrives in conversations, appointments, errands, responsibilities, routines—and things we remember too late.</p><p>MINE AI helps gather that messy input and shape it into a day you can actually see.</p><div className="word-cloud"><span>Conversations</span><span>Appointments</span><span>Errands</span><span>Responsibilities</span><span>Routines</span><span>“Don’t forget…”</span></div></div></div></section>
  <section id="how-it-works" className="section shell"><div className="section-head"><div><p className="section-kicker">How it works</p><h2>From scattered thoughts<br/>to a day that makes sense.</h2></div><p>No rigid setup. Start where you are and stay in control of the result.</p></div><div className="step-grid">{steps.map(([n,t,d])=><article className="step-card" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section id="features" className="section feature-section"><div className="shell"><div className="section-head"><div><p className="section-kicker">Built for the day you have</p><h2>Planning that feels<br/>less like planning.</h2></div><p>Simple tools that help you move from “there’s a lot going on” to “I know what comes next.”</p></div><div className="feature-grid">{features.map(([t,d],i)=><article className={`feature-card feature-${i}`} key={t}><span className="feature-icon" aria-hidden>{['◉','✎','✦','↻','◷','⌁','☁','✓'][i]}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="section shell"><div className="center-head"><p className="section-kicker">Made for real people</p><h2>Different lives. Same crowded day.</h2></div><div className="people-grid">{people.map(([t,d],i)=><article key={t}><span>{['01','02','03','04'][i]}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="section demo-section"><div className="shell demo-grid"><div><p className="section-kicker light">One thought. A clear plan.</p><h2>Say it the way<br/>it comes to you.</h2><p>MINE AI finds the shape inside a busy sentence, then gives you something useful to review.</p><div className="demo-input"><span className="mic">●</span><q>Gym before work, meeting at 11, groceries after work, call dad tonight.</q></div></div><div className="demo-output"><div className="demo-title"><div><small>TODAY · TUESDAY</small><h3>Your day</h3></div><span>4 items</span></div>{[['6:30','Gym','Wellbeing'],['9:00','Work','Work'],['11:00','Team meeting','Work'],['5:30','Groceries','Errand'],['8:00','Call Dad','Personal']].map(([t,x,c],i)=><div className="demo-row" key={x}><time>{t}</time><span className={`mini-dot md-${i}`}/><div><strong>{x}</strong><small>{c}</small></div>{i===0&&<span className="done">✓</span>}</div>)}</div></div></section>
  <section className="section shell trust"><div><p className="section-kicker">Privacy without the fine-print theater</p><h2>Your plans are personal.<br/>We treat them that way.</h2><Link className="text-link" href={ROUTES.privacy}>Read our Privacy Policy →</Link></div><div className="trust-list">{['Voice is temporarily processed for transcription.','MINE AI uses secure HTTPS connections.','Delete your account and associated account data.','MINE AI does not sell user data.'].map((x,i)=><div key={x}><span>{i+1}</span><p>{x}</p></div>)}</div></section>
  <section id="pricing" className="section pricing-section"><div className="shell"><div className="center-head"><p className="section-kicker">Simple pricing</p><h2>Start planning for free.</h2><p>Move to Pro when you want more from MINE AI.</p></div><div className="price-grid"><article className="price-card"><p className="plan-name">{PRICING.free.name}</p><div className="price">{PRICING.free.price}</div><p>Try the core MINE AI experience.</p><ul>{['Limited AI planning','Core planning experience','Tasks and daily organization'].map(x=><li key={x}>✓ {x}</li>)}</ul><a href="#early-access" className="outline-button">Join early access</a></article><article className="price-card featured"><span className="popular">EARLY ACCESS</span><p className="plan-name">{PRICING.pro.name}</p><div className="price">{PRICING.pro.price}<small>{PRICING.pro.cadence}</small></div><p>More room to plan life your way.</p><ul>{['More AI planning access','Voice planning','Cloud sync','Full planning workflow','Smart reminders','Future Pro improvements'].map(x=><li key={x}>✓ {x}</li>)}</ul><a href="#early-access" className="button">Join early access</a><small>Subscription availability may vary during early access.</small></article></div></div></section>
  <section id="faq" className="section shell faq-section"><div><p className="section-kicker">Questions, answered</p><h2>The useful details.</h2><p>Still wondering about something?</p><Link href={ROUTES.support} className="text-link">Contact support →</Link></div><div className="faq-list">{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span aria-hidden>+</span></summary><p>{a}</p></details>)}</div></section>
  <section id="early-access" className="final-cta"><div className="shell"><p className="eyebrow light"><span/>MINE AI</p><h2>Your life is already busy.<br/><em>Planning it shouldn’t be.</em></h2><p>MINE AI is currently preparing for public Android release.</p><a className="button button-light" href="mailto:support@usemineai.com?subject=MINE%20AI%20early%20access">Get early access <span aria-hidden>→</span></a></div></section>
  </main><Footer/></>}
