import type { Metadata } from 'next';
import { DeleteRequestForm } from '@/components/delete-request-form';
import { LegalLayout } from '@/components/site-shell';
import { SITE } from '@/lib/site';
export const metadata:Metadata={title:'Delete your MINE AI account',description:'Delete your MINE AI account in the app or initiate a verified account-deletion request from the web.',alternates:{canonical:'/delete-account'}};
const removed=['Profile','Tasks and items','Routines and routine logs','Memory and day history','Push registrations','Account-linked AI usage records','Signed-in AI reports','Other account-linked app data'];
export default function DeleteAccount(){return <LegalLayout eyebrow="Account control" title="Delete your MINE AI account" intro="Account deletion is permanent. You can delete inside MINE AI or begin a verified deletion request here without reinstalling the app.">
<div className="notice danger"><strong>Before you continue</strong><p>Deletion cannot be undone. We may retain limited records where reasonably required by law, security, fraud prevention or dispute resolution.</p></div>
<section className="option-card"><span className="option-number">01</span><div><h2>Delete in the MINE AI app</h2><p>If you can sign in to the app, this is the most direct option.</p><div className="breadcrumb" aria-label="In-app deletion path"><span>Open MINE AI</span><b>→</b><span>Me</span><b>→</b><span>Delete Account</span></div><p>Follow the confirmation steps shown in the app.</p></div></section>
<section className="option-card"><span className="option-number">02</span><div><h2>Initiate deletion from the web</h2><p>This website does not have account authentication and cannot delete an account directly. Submit the form below to prepare an email request. MINE AI Support will require identity verification before any deletion occurs; an email address alone is not sufficient authority.</p><DeleteRequestForm/><p>If your email app does not open, email <a href={`mailto:${SITE.supportEmail}`}>{SITE.supportEmail}</a> with the subject “MINE AI account deletion request.” Include your account email, but never send your password.</p></div></section>
<h2>Data the request may remove</h2><p>Once ownership is verified and deletion is processed, account deletion may remove:</p><div className="removal-grid">{removed.map(x=><span key={x}>✓ {x}</span>)}</div>
<h2>What happens next</h2><ol><li>You initiate the request from this page.</li><li>Support sends ownership-verification instructions.</li><li>After successful verification, the account-deletion process begins.</li><li>You receive confirmation when the request has been handled.</li></ol><p>Response times vary with request volume and verification needs. We will respond as reasonably practicable without promising a fixed service level.</p>
</LegalLayout>}
