import type { Metadata } from 'next';
import { LegalLayout } from '@/components/site-shell';
import { EFFECTIVE_DATE, SITE } from '@/lib/site';
export const metadata:Metadata={title:'Terms of Use | MINE AI',description:'Terms governing use of MINE AI.',alternates:{canonical:'/terms'}};
export default function Terms(){return <LegalLayout eyebrow="Legal" title="Terms of Use" intro={`Effective ${EFFECTIVE_DATE}. Please read these terms before using MINE AI.`}>
<h2>1. Acceptance</h2><p>By accessing or using MINE AI, you agree to these Terms and our Privacy Policy. If you do not agree, do not use the service.</p>
<h2>2. Eligibility</h2><p>You must be legally able to agree to these Terms in your location. If you use MINE AI for someone else or an organization, you confirm that you have authority to do so.</p>
<h2>3. Early access</h2><p>MINE AI is preparing for public Android release and may be offered in early access. Features may be incomplete, change, stop working or be removed as the product develops. Feedback is welcome but does not create an obligation to implement it.</p>
<h2>4. Accounts</h2><p>You are responsible for accurate account information, safeguarding your credentials and activity under your account. Notify us promptly if you suspect unauthorized use.</p>
<h2>5. Acceptable use</h2><p>Use MINE AI lawfully and only for its intended personal planning purpose. Do not interfere with the service, bypass limits, probe for vulnerabilities, impersonate others, introduce malicious code, scrape the service, infringe rights, or use output to harm, deceive or unlawfully discriminate against anyone.</p>
<h2>6. AI-generated output</h2><p>MINE AI uses artificial intelligence to help organize information. AI output may be inaccurate, incomplete, delayed or unsuitable. You remain responsible for reviewing plans and for your actions and decisions. MINE AI is not a substitute for professional judgment and does not provide medical, legal, financial or other professional advice. Do not rely on it for emergencies or safety-critical decisions.</p>
<h2>7. Subscriptions and payments</h2><p>Some features may require a paid subscription when subscriptions are available. Price, billing period, included features and any trial terms will be shown before purchase in the relevant app marketplace. Taxes may apply. Subscription availability may vary during early access.</p>
<h2>8. Cancellation</h2><p>You can manage or cancel an app-store subscription through the marketplace account used to purchase it. Cancellation generally stops renewal while access may continue through the paid period, subject to marketplace rules. Refunds are handled under applicable law and marketplace policies.</p>
<h2>9. Service availability</h2><p>We aim to provide a reliable service but do not promise uninterrupted or error-free operation. We may modify, suspend or discontinue features for maintenance, security, legal or product reasons.</p>
<h2>10. Intellectual property</h2><p>MINE AI, including its software, design, branding and service content, is owned by MINE AI or its licensors and protected by applicable law. These Terms give you a limited, personal, non-exclusive, non-transferable right to use the service.</p>
<h2>11. Your content</h2><p>You retain rights you have in content you provide. You grant us a limited permission to host, process, transmit and display it only as needed to operate, secure and improve MINE AI and meet legal obligations. You confirm you have the right to provide that content.</p>
<h2>12. Termination</h2><p>You may stop using MINE AI and delete your account. We may restrict or terminate access when reasonably necessary for a breach of these Terms, security, legal compliance or protection of users and the service.</p>
<h2>13. Disclaimers and liability</h2><p>To the extent permitted by law, MINE AI is provided “as is” and “as available” without warranties not expressly stated here. To the extent permitted by law, MINE AI and its operators will not be liable for indirect, incidental, special, consequential or punitive damages, or loss of data, profits or opportunities arising from use of the service. Nothing in these Terms excludes rights or liability that cannot legally be excluded.</p>
<h2>14. Governing terms</h2><p>The governing law and forum will be determined by the operator’s finalized legal jurisdiction and applicable consumer law. Until that information is published, mandatory rights and dispute rules in your location may apply. This section should be updated before broad commercial launch.</p>
<h2>15. Changes and contact</h2><p>We may update these Terms as the service changes. Updated terms will be posted with a revised effective date, and additional notice will be provided when appropriate. Contact <a href={`mailto:${SITE.supportEmail}`}>{SITE.supportEmail}</a> with questions.</p>
</LegalLayout>}
